name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    # - name: Set NGINX_VERSION
    #   run: echo "NGINX_VERSION=$(curl -s 'http://nginx.org/en/download.html' |  sed 's/</\'$'\n''</g' | sed -n '/>Stable version$/,$ p' | egrep -m1 -o '/download/nginx-.+\.tar\.gz'| egrep -Eo '([0-9]+.[0-9]+.[0-9]+)')" >> $GITHUB_ENV
    # - name: Set CRS_VERSION
    #   run: echo "CRS_VERSION=$(wget -q -O- https://api.github.com/repos/coreruleset/coreruleset/releases/latest | jq -r '.name' | sed 's/v//')" >> $GITHUB_ENV
    # - name: Install jq
    #   run: sudo apt-get install -y jq
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Versions
    #   run: echo "Nginx version is $NGINX_VERSION and CRS version is $CRS_VERSION"
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: thib4ut/mdns-repeater:latest
        # build-args: |
        #   "NGINX_VERSION=${{ env.NGINX_VERSION }}"
        #   "CRS_VERSION=${{ env.CRS_VERSION }}"      